### ISSUE TITLE
feat: don't require 24/7 hosting

### ISSUE THREAD

**Issue by Canny1913** [reisxd/TizenTube#1]
i cant put the linux cd in my computer

**Comment by reisxd** [comment]
This is sadly not possible, as the script connects to the TV and runs a debugger whenever you launch the app. It's expected to run it 24/7 to have it always work. You can still use even your phone (with Termux) to do this.

**Comment by Canny1913** [comment]
EXPLOD

**Comment by reisxd** [comment]
> EXPLOD

no

**Comment by Canny1913** [comment]
eat a pipebomb
