### ISSUE TITLE
[Request] Return Youtube Dislike

### ISSUE THREAD

**Issue by daisuke1227** [reisxd/TizenTube#100]
It'll be awesome to see the dislikes and stuff (here's source code) [ReturnYoutubeDislike](https://github.com/Anarios/return-youtube-dislike)

**Comment by reisxd** [comment]
I don't think anyone even checks how many likes a video has gotten on a TV. I don't think its worth the effort to add it.

**Comment by daisuke1227** [comment]
okay then

**Comment by Julmik647** [comment]
You may try using [VacummTube](https://github.com/shy1132/VacuumTube)'s Return YouTube dislikes implementation. It also uses YouTube leanback so it should be possibile as Kong as this code isn't integrated with VacummTube.

**Comment by woyabi** [comment]
I've recommended this app to a lot of folks, some with similar tastes to me and an overwhelming number without, and of the several features we all would like and really benefit from is the dislike counter, as we usually just transition from our laptops to tvs in the evening after work

please find a way to implement it, you've already integrated quite a bit and this feature would be absolutely perfect
