### ISSUE TITLE
Upgrade from TIZEN 7 to TIZEN 8

### ISSUE THREAD

**Issue by xaviferreres** [reisxd/TizenTube#102]
Hello,
I have a SAMSUNG TQ75Q80CATXXC 2023 TV with TIZEN 7 OS.
I installed Tizentube and it works fine (thanks a lot!).
For a few days now I've been getting messages on the TV about an update to upgrade to TIZEN 8.
If I do this, will Tizentube still work fine or will I have to reinstall it as you mention in the TizenBrew installation instructions?:
_"Note that you can't install TizenBrew to your TV if your TV is Tizen 8 or newer (2024+). **You'll have to rebuild TizenBrew from source** to install it on newer TVs"_

Thank you very much.

**Comment by reisxd** [comment]
TizenBrew will get uninstalled and you will have to rebuild it. Also, not related to TizenTube.

**Comment by xaviferreres** [comment]
In your opinion, is it worth upgrading to TIZEN 8?
Thanks.
