### ISSUE TITLE
[ERROR] Cannot find module. 

### ISSUE THREAD

**Issue by n0w33d** [reisxd/TizenTube#104]
Upon launching this module the following error is displayed

> ! Error: Could not find the module @foxreis/tizentube

No further messages appear to allow for troubleshooting. 

Please let me know what other info you need to help resolve. 

Tangent:  is there a way for me to fork your repo and host the TizenTube module for myself?

**Comment by KawaKode** [comment]
Hello, same thing here on TizenBrew 1.4.3

**Comment by kelvinkad** [comment]
Same thing here

**Comment by kelvinkad** [comment]
@reisxd why this os happening? Any idea?

**Comment by kelvinkad** [comment]
Any news about this?

**Comment by kelvinkad** [comment]
@reisxd

**Comment by Nghia323223** [comment]
So am I, happened on Tizen 1.4.2/.3.

**Comment by reisxd** [comment]
Duplicate of https://github.com/reisxd/TizenBrew/issues/75. Also not related to TizenTube.
