### ISSUE TITLE
quick start

### ISSUE THREAD

**Issue by michlq** [reisxd/TizenTube#105]
hi.
can someone tell me how he did it with the quick start symbol?

https://youtu.be/YjzH1y1FJdI

**Comment by michlq** [comment]
Why closed it again straight away? I just wanted to know if anyone here has any idea how to create the symbol like in the video, and not whether it is planned for the future.

**Comment by reisxd** [comment]
> Why closed it again straight away? I just wanted to know if anyone here has any idea how to create the symbol like in the video, and not whether it is planned for the future.

Because it's not an issue and that was possible with older TizenTube, before TizenBrew.

**Comment by michlq** [comment]
Sorry, unfortunately you can't ask a direct question here. 

You said: "technically still possible if you know how" - that's exactly why I asked? I don't know, but I'd like to know. 
And I thought if anyone could answer this, it would be here, right? It's a great thing that you've developed, but it would be more convenient to get there directly with "one click" (as you can see in the video).
