### ISSUE TITLE
im still seeing some ads

### ISSUE THREAD

**Issue by mxtmk** [reisxd/TizenTube#11]
im running the nodejs on my laptop and all is installed as instructed and running the launcher app. also to note everytime i launch the app on the tv i get this message: why is this happening for 10 sec and then the youtube app starts.

**Comment by ameenalasady** [comment]
> note everytime i launch the app on the tv i get this message: why is this happening for 10 sec and then the youtube app starts.

This is somewhat normal but 10 seconds seems excessive. Usually lasts only ~1 second for me. What I suspect is you have a weak internet connection on either your TV or your laptop. Could you try the Android app and see if you get the same issue?

**Comment by reisxd** [comment]
> > note everytime i launch the app on the tv i get this message: why is this happening for 10 sec and then the youtube app starts.
> 
> This is somewhat normal but 10 seconds seems excessive. Usually lasts only ~1 second for me. What I suspect is you have a weak internet connection on either your TV or your laptop. Could you try the Android app and see if you get the same issue?

It's probably their TV. YT should load instantly and if it doesn't, they have slow internet on their TV. I don't know why they might still have ads. I can't try to reproduce because I recently broke my RPIs ethernet dongle. I'll test today, hopefully.
