### ISSUE TITLE
Long press menu is not context senstive

### ISSUE THREAD

**Issue by cremor** [reisxd/TizenTube#110]
I saw that you added a custom long press menu recently. Thanks for that!
Right now that menu always has the same items. Would it be possible to make it context specific like the original menu is? E.g. offer:
- "not interested" options on the home screen
- "remove from watch later" options in the watch later playlist

**Comment by reisxd** [comment]
Not possible. Spoof your User-Agent if you require it.

**Comment by cremor** [comment]
I'm already using the option "use device user agent" in TizenBrew. And I tested all other availabe options. None gave a long press menu previously.
Or do you mean something else?

**Comment by reisxd** [comment]
> I'm already using the option "use device user agent" in TizenBrew. And I tested all other availabe options. None gave a long press menu previously. Or do you mean something else?

The other options (Samsung TV models, to be specific).
