### ISSUE TITLE
Question regarding apk and standalone

### ISSUE THREAD

**Issue by frogc0d3** [reisxd/TizenTube#111]
1. What is the purpose of the APK version of TizenTube in the releases, and where can its source be found?

2. Is it possible to use TizenTube and TizenBrew to create a complete standalone version of the TizenTube app? If there are multiple apps in TizenBrew, it would be great if it were possible to pin those app icons directly to the apps bar. If that is not possible, would it be possible for me to create multiple TizenBrew compilations, each featuring a single app?

If that's not possible, it's still a great app, and I'm glad it doesn't require a dedicated server.

**Comment by reisxd** [comment]
1. TizenTube Server in the releases is from the old days of TizenTube without TizenBrew. TizenTube used to require two apps (one being a launcher, one being the app) installed on the TV and required a server running. This changed with TizenBrew Standalone.

2. In theory, you could modify TizenBrew app to only launch TizenTube and nothing else. But TizenBrew is for modifying apps and "installing" new apps without using Tizen Studio by being modular, so it's out of scope for TizenBrew.

**Comment by frogc0d3** [comment]
Thank you for the information and the super quick reply! Just one last question: Is it theoretically possible to make an app like TizenBrew pin icons to the apps bar? For example, if I have two apps installed within TizenBrew, could I have the ability to pin two icons to the apps bar that, when clicked, would open the respective apps within TizenBrew? I'm not asking this to be added as a feature; I'm just asking if such a method is even possible.

**Comment by reisxd** [comment]
This isn't possible due to Tizen TV not having such feature.
