### ISSUE TITLE
Launcher times out

### ISSUE THREAD

**Issue by Bierdusche** [reisxd/TizenTube#12]
Hi there,
while launching TizenTube through the Launcher app. The launcher app says waiting for Tizentube to start.....
Then times out.
Apps and debugger are installed as in installation guide.
Any ideas?

**Comment by ameenalasady** [comment]
Are you using the Android app or node?

**Comment by Bierdusche** [comment]
node

**Comment by reisxd** [comment]
You probably didn't change the IP variable in the Launcher.
