### ISSUE TITLE
Minimum Android requirement

### ISSUE THREAD

**Issue by pubct** [reisxd/TizenTube#15]
Sorry for bothering.
I think I did my diligence to read things first, but during app installation, I get failed to parse the package on my Android 5.0 device.

I guess there's a minimum Android requirement for the app?

**Comment by reisxd** [comment]
The Android version requirement is arbitrary. It can basically work on any Android device, probably Android >=4. I can change it to include A4.

**Comment by DomyK** [comment]
> The Android version requirement is arbitrary. It can basically work on any Android device, probably Android >=4. I can change it to include A4.

Yes, please change the minimum Android version for installing and running the application, because now the application can only be installed on Android 8+.
