### ISSUE TITLE
Launcher crash on Tizen 2.4

### ISSUE THREAD

**Issue by AkimoA** [reisxd/TizenTube#20]
hi, 

Im running a 2016 model with Tizen 2.4  and I get it installed and running  but as soon I klick the Launcher app it crashes back to SmartHub . is this related to the release year or the Tizen Version ?

nodejs server/debugger is running and connected while that happens .

the whole project obviously says (2017-and on )  but would there be a workaround maybe  or at least a log to see why it immediately crashes .

**Comment by reisxd** [comment]
That's intentional. The app exists once the WS sends `ok` event. Try enabling the `isTizen3` property in config.json and report back.
