### ISSUE TITLE
prebuild wgt support possible?

### ISSUE THREAD

**Issue by shubhendusaurabh** [reisxd/TizenTube#25]
Hi, is it possible to have prebuilt wgt file?

Here is jellyfin build that does this: https://github.com/jeppevinkel/jellyfin-tizen-builds

installation process would be simpler then.

Thanks

**Comment by ThowZzy** [comment]
So far, no. Because you have to hardcode your IP inside the app. 
But thats only true for the launcher app.

**Comment by reisxd** [comment]
> So far, no. Because you have to hardcode your IP inside the app. But thats only true for the launcher app.

Well, I could always make it so you can change it in the app.

**Comment by ThowZzy** [comment]
> > So far, no. Because you have to hardcode your IP inside the app. But thats only true for the launcher app.
> 
> Well, I could always make it so you can change it in the app.

yeah thought about that, just more work lol

**Comment by reisxd** [comment]
Closing due to TizenTube becoming a TizenBrew module.
