### ISSUE TITLE
Ad Block doesn't work

### ISSUE THREAD

**Issue by jonasftw** [reisxd/TizenTube#28]
I got the setup to work successfuly, I can even see the notification **Press [GREEN] to open YTAF configuration screen**
However ads are still there

**Comment by jonasftw** [comment]
Skippable in-stream ads.
Non-skippable in-stream ads.

**Comment by Jeje292** [comment]
I had the same @jonasftw, so I : 

1- rebooted my TV (Tizen 6.5) with long press 2 sec + start
2- rebooted my PC and launch node
3- started the launcher from TV
Result : no ads for me
Can you try this ?

& thank you @reisxd !!

**Comment by reisxd** [comment]
I can't really reproduce this issue, as it could be an A/B test. Either something went wrong or there's a new A/B test.
