### ISSUE TITLE
Rebrand

### ISSUE THREAD

**Issue by oSumAtrIX** [reisxd/TizenTube#3]
I suggest using a better name that gives more insight into the project. Currently, it is named TizenTube, which, if someone comes by, will never know that it blocks ads for YouTube. A name should be used so that if someone sees the name, he instantly knows what this project does. This way, they will check it out. As of now, I can imagine that many people saw the name but didn't bother to check it further out because they couldn't infer what the project offers from the name.

**Comment by shrihanDev** [comment]
Holy shi-

**Comment by morethanhater** [comment]
why ReVanced then? It doesn't contain even the slightest part of YouTube naming

TizenTube consists of both OS name and a part of YouTube, so i see no problem with naming here

**Comment by oSumAtrIX** [comment]
@morethanhater Where did I say ReVanced?

**Comment by morethanhater** [comment]
duh, you're so hard to uptake

**Comment by reisxd** [comment]
In my opinion, there's not a good choice of branding for TizenTube. There's no way to have a better name without it being longer/sounding weird.

**Comment by shrihanDev** [comment]
ReTizenTube :trollface:

**Comment by oSumAtrIX** [comment]
@reisxd The issue is that people will not know what this project is from the name, thus, will never bother to checkout. Reopen if it matters.

**Comment by reisxd** [comment]
> @reisxd The issue is that people will not know what this project is from the name, thus, will never bother to checkout. Reopen if it matters.

Is there any example that you could give?
