### ISSUE TITLE
[ENHANCEMENT] Video Play Speed

### ISSUE THREAD

**Issue by SobanAmin** [reisxd/TizenTube#30]
Thank you so much. Got it working on linux mint after a lot of fiddling with nodejs.
I have noticed that video playback speed option is missing in this app. It would really mean alot if it can be added soon.

Peace!

**Comment by reisxd** [comment]
Integrating this to the main UI (YouTube Video Player settings) is probably not an easy task. Whenever I add a new element, it gets overwritten. And I am not insane enough to reverse engineer minified JS code. Probably I could do something more close to the settings page.

**Comment by SobanAmin** [comment]
Much appreciated. Thanks

**Comment by reisxd** [comment]
Added in 5a01cb03abe69e3ed7983d6fdb34cdd898575777.
