### ISSUE TITLE
Homeassistant addon for server

### ISSUE THREAD

**Issue by gunsha** [reisxd/TizenTube#38]
First of all, thanks so much for this! finally I don't hate watching youtube on my TV after a year of using it.
I made a simple docker file and config to run the server inside Homeassistant on my Raspberry Pi

https://github.com/gunsha/TizenTubeHassioServer

it's not being published or anything, i don't think i'm going to put the time for that, but it runs as a local addon without any issues, also the dockerfile should serve for the people wanting to use it on docker (#4)

**Comment by reisxd** [comment]
Closing because this is not an issue.
