### ISSUE TITLE
Multiple cases of audio playback being good while video keeps lagging

### ISSUE THREAD

**Issue by IntelCorei5-8350u** [reisxd/TizenTube#51]
Well that's what some told me when they saw my tutorial & introduction of this mod, translated to Vietnamese in a facebook group.
I have recommended them to restart their TVs, uninstall unnecessary apps and nothing worked
One guy informed me his TV model, AU7002. Video will lag no matter which resolution was set, and happen mostly with music videos.
It did not happen to me though. Only a very few cases reported this problem back to me, around 4-5 people out of 2-3k of facebook likes and youtube views.

**Comment by reisxd** [comment]
The speed of the video should be changed to 1.0001 in Video Speed Settings (the blue button).

**Comment by NidzaKS** [comment]
Thanks a lot!
