### ISSUE TITLE
The application cannot be executed due to expiration of the validity period.

### ISSUE THREAD

**Issue by moon-sh0t** [reisxd/TizenTube#57]
Error started on Friday 24-May. Pops up and kills application as soon as you click on icon.

**Comment by MichsonKichson** [comment]
Same for me

**Comment by c4dee** [comment]
Same here.

**Comment by PottiMc** [comment]
I just installed TubeBrew on a brand new QN85C and had the same troubles when using the USB package of TizenBrew. Now it works flawlessly when I used the TizenStudio install method of TizenBrew.

**Comment by NidzaKS** [comment]
> I just installed TubeBrew on a brand new QN85C and had the same troubles when using the USB package of TizenBrew. Now it works flawlessly when I used the TizenStudio install method of TizenBrew.

Can you make a video how u did that? I failed that in many ways.

**Comment by DerDom2010** [comment]
Working here again after using TizenStudio. Followed the instructions on the TizenBrew GIT Page. 
It was important to delete the App first.

best wishes

**Comment by PottiMc** [comment]
> > I just installed TubeBrew on a brand new QN85C and had the same troubles when using the USB package of TizenBrew. Now it works flawlessly when I used the TizenStudio install method of TizenBrew.
> 
> Can you make a video how u did that? I failed that in many ways. 

Actually it is described pretty well here on GitHub. There is nothing I could add.

1. Make sure you uninstall everything old from TizenBrew from your TV.
2. Install TizenStudio GUI edition on your computer including the TV extensions
3. Download the TizenBrew packages.
4. Make sure you are in the same network and your TV developer mode is pointing to the IP of your computer (double check PC: Maybe You have Wifi and LAN switched on?) Make sure to restart TV after setting the developer mode to on.
4. Connect to your TV in the TizenStudio Device Manager.
5. Do the magic with your command line tool of choice and the commands mentioned.

**Comment by NidzaKS** [comment]
> > > I just installed TubeBrew on a brand new QN85C and had the same troubles when using the USB package of TizenBrew. Now it works flawlessly when I used the TizenStudio install method of TizenBrew.
> > 
> > Can you make a video how u did that? I failed that in many ways. 
> 
> Actually it is described pretty well here on GitHub. There is nothing I could add.
> 
> 1. Make sure you uninstall everything old from TizenBrew from your TV.
> 2. Install TizenStudio GUI edition on your computer including the TV extensions
> 3. Download the TizenBrew packages.
> 4. Make sure you are in the same network and your TV developer mode is pointing to the IP of your computer (double check PC: Maybe You have Wifi and LAN switched on?) Make sure to restart TV after setting the developer mode to on.
> 4. Connect to your TV in the TizenStudio Device Manager.
> 5. Do the magic with your command line tool of choice and the commands mentioned.

Did it!  Now I have it on 2 tvs, one is 2018 & workink fine and the other one 2023 cu7102 working fine but video is laggy?

**Comment by max0093** [comment]
I keep getting this error while trin to install using Tizen Studio
install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
can somebody help?

**Comment by reisxd** [comment]
There isn't really a way to fix this. You could repackage TizenBrew widget as an USB Demo again or you could use either TizenBrew Installer or use sdb/tizen command.

Might be fixed when I release a new update.
