### ISSUE TITLE
Certificate issue while installing using Tizen Studio

### ISSUE THREAD

**Issue by max0093** [reisxd/TizenTube#59]
I'm facing this error whenever I try to install.. tried deleting my certificate profile and creating a new one but it didn't help

install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
 
![image](https://github.com/reisxd/TizenTube/assets/171830851/e9ac4760-4b94-4f2c-b9cf-dfddc9b50bed)

**Comment by reisxd** [comment]
What's your TVs model?

**Comment by reisxd** [comment]
It should work. No idea why. You have a 2022 model TV, which the certificate should be compatible with.

**Comment by max0093** [comment]
The Amazon page where I bought the tv states that it's "QA55Q60DAUXEG [2024 Model]".. not sure if this is relevant information or not.
Any advice or something to try?

**Comment by reisxd** [comment]
Oh, I see. Samsung loves to reuse the same model. If it is 2024 model, then you'll have to rebuild TizenBrew with your own certificate. You should see the GitHub Workflow on how the dist/index.js file is built.

If only Tizen/Samsung updated their CLI tools and fixed Tizen certificate creation on IDE.
