### ISSUE TITLE
[Request] Manual SponsorBlock skipping 

### ISSUE THREAD

**Issue by abdellahaski** [reisxd/TizenTube#61]
First Thanks for your amazing work.
I just installed the app on my Samsung TV, everything seems to work as expected but I'm missing a feature coming from SmartTube on my Tv Box, it's the ability to manually Skip SponsorBlock segments, automatic skips works as expected, but I would like to have the ability to manually skip or not as sponsor segments.

**Comment by Odie20XX** [comment]
I'd like to +1 this one. Ran into some videos where there were parts of the video skipped which weren't a valid SponsorBlock.
Sure, I could rewind to check if it was valid or not, but asking to skip would save some time :)

Or an option to disable modules?

**Comment by abdellahaski** [comment]
If I'm not mistaken, there is an option to disable SponsorBlock specific detections & skips entirely.
But yeah asking to skip would really be better

**Comment by beingkha3** [comment]
> If I'm not mistaken, there is an option to disable SponsorBlock specific detections & skips entirely. But yeah asking to skip would really be better

Where is the option to disable sponsor block?
