### ISSUE TITLE
did not work on 2023 qn90 TV

### ISSUE THREAD

**Issue by linkysys** [reisxd/TizenTube#69]
First of all, thanks for developing something like this. I enabled developer mode and added the Host pc ip to 127.0.0.1, rebooted TV, then attempted to load tizentube from your installer URL at tizentube.live/installer. Received error message "The NaCI module is not ready yet. You either have a slow connection or your TV is too new. Please try again."

I'm assuming my TV is too new? 

2023 QN85QN90CAFXZA 
Software version: T-PTMCAKUC-1421.1, E0371410, BT-S
Status code: 50301_AD2AE14_EJ5
sub-micom version: T-PMCINTV-1006

**Comment by linkysys** [comment]
I re-read and see that the installer only works on tv's through 2021. I'll have to attempt your other install method. If there is a video or step by step instructions for dummies somewhere let me know LOL.

**Comment by linkysys** [comment]
Update-- attempted demo USB install. TV does not launch app automatically. Checked for installed apps and nothing. Tried to manually run wpt file by browsing to it in TV menu and it did not work. Possibly user error. I did leave the file structure as-is and extracted the complete demo package to a USB. The USB was a smaller drive but the file contents aren't massive

Also attempted to install using CLI command line method but could not connect Windows PC to TV IP address. I'm assuming this must be configured and run through CMD window. Struggled to set global path so had to use CD to open bin folder before commands would work. Again, probably user error with something basic.

**Comment by MinaMalaak** [comment]
yes i have the same issue ! please help

**Comment by reisxd** [comment]
See the new update for TizenBrew.

**Comment by linkysys** [comment]
I was using Tizenbrew 1.2.1.zip. Is that not the newest version?

**Comment by MinaMalaak** [comment]
whenever i connect the usb to the tv it shows nothing...the updater only works and i dont know how to complete the process
can you please help ?
