### ISSUE TITLE
Bypass YouTube Block

### ISSUE THREAD

**Issue by noideastowork** [reisxd/TizenTube#84]
Could you please consider adding tools for bypass blocking? 

As Russia is now starting to block YouTube, it would be great if the app had an option to enable traffic via a proxy, for example. I don't mean built-in tools (that would be too bold to ask for), just the ability to use a proxy. 

Since Russia is now blocking YouTube, it would be great if the app had an option to bypass restrictions.  I don't mean built-in tools (that would be too good to ask for.), but, for example, just the option to use a proxy server in app.

**Comment by reisxd** [comment]
Proxies are not supported on Tizen.

**Comment by THEBIGMISHA** [comment]
But isn't YouTube launched as a web page? You can also write the URL of the web proxy at the beginning.
