### ISSUE TITLE
[Feature Request] Option to add TizenTube to the AppList (Home screen)

### ISSUE THREAD

**Issue by leuldereje96** [reisxd/TizenTube#89]
If possible please give us the option to add youtube to the application list instead of always going to Tizen Brew to open youtube.
(the youtube you see in the picture is the one that comes with the TV)

![20240925_082319](https://github.com/user-attachments/assets/56fbef63-9c57-44ac-8836-86adf557d325)

**Comment by reisxd** [comment]
This is not possible. 

While technically, there could be an app that launches TizenBrew, it's not TizenTube's or TizenBrew's job to install that application.

Also, there's no shortcuts on Tizen.
