### ISSUE TITLE
bug: the configuration screen does not show up

### ISSUE THREAD

**Issue by reisxd** [reisxd/TizenTube#9]
# Issue
TizenTube's current mods have been forked over from [here](https://github.com/webosbrew/youtube-webos/). While it still works, the configuration screen cannot be enabled. This is due to not registering the key event for the configuration screens button. I did try to register it before, but it sadly did not work.  There's either a problem with the Tizen JS API or the key event code is wrong.

**Comment by oSumAtrIX** [comment]
If it is forked, please use the "fork" functionality for correct semantics.

**Comment by reisxd** [comment]
> If it is forked, please use the "fork" functionality for correct semantics.

The whole repository is not a fork.
