### ISSUE TITLE
Keyboard keys not working

### ISSUE THREAD

**Issue by xaviferreres** [reisxd/TizenTube#92]
I use a Logitech K600 keyboard (bluetooth) connected to my SAMSUNG Q80C QLED 75" Smart TV 2023 (Tizen 7.0).
The problem is that when I try to search on Tizentube with the keyboard, many keys do not work (G,H,J,U, etc).
Is there any solution to fix this problem?
Thank you very much.

**Comment by reisxd** [comment]
This is an issue in YouTube TV client, not TizenTube.

**Comment by xaviferreres** [comment]
Let me see if I understand correctly:
Although the keyboard works correctly for me in the genuine Youtube app, it is normal to have problems with keyboards in TizenTube and there is no solution, is that correct?
Thank you very much.
