### ISSUE TITLE
Request for a WebOS-Compatible Version of TizenTube

### ISSUE THREAD

**Issue by Ham44id** [reisxd/TizenTube#96]
Dear reisxd, 

Thank you for developing the fantastic TizenTube application.

I own a TV with WebOS and would like to know if it’s possible to provide a version compatible with this system for IPK format. ☹️

I appreciate your efforts and look forward to your response.

Best regards

**Comment by reisxd** [comment]
[youtube-webos](https://github.com/webosbrew/youtube-webos) already exists and TizenTube is a module for TizenBrew. While it is possible to build TizenTube for webOS, TizenTube's purpose is for Tizen TV devices, not webOS devices.
