### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by DavidOliM** [reisxd/TizenTube#98]
I did the installation process and added the module but I can only see a gray square in tizenbrew's main screen and nothing happens. I tried removing the module and adding it again but still nothing.

![20241108_184738](https://github.com/user-attachments/assets/25963c1c-f034-4163-a658-03d0b1d46717)
![20241108_184802](https://github.com/user-attachments/assets/86c6cd18-2ad8-41a5-9d15-4610c9f55774)

**Comment by Ian-Garrigan** [comment]
Same problem for me. Did you find a solution for it?

**Comment by DavidOliM** [comment]
@Ian-Garrigan Yes, I forgot to change the host PC IP address to 127.0.0.1 and reboot the TV. After I did that it worked

**Comment by Ian-Garrigan** [comment]
> @Ian-Garrigan Yes, I forgot to change the host PC IP address to 127.0.0.1 and reboot the TV. After I did that it worked

Alright, seems like the latest version is working fine for me now 👍🏻
